export default {
  fontMain: '"Open Sans", sans-serif',
  fontSecondary: 'fontMain',

  fontWeightThin: '200',
  fontWeightLight: '300',
  fontWeightNormal: '400',
  fontWeightBolder: '500',
  fontWeightBold: '600',
  fontWeightUltraBold: '800',

  baseFontSize: '16px',
  fontSizeXlg: '1.25rem',
  fontSizeLg: '1.125rem',
  fontSize: '1rem',
  fontSizeSm: '0.875rem',
  fontSizeXs: '0.75rem',

  radius: '0.375rem',
  padding: '1.25rem',
  margin: '1.5rem',
  lineHeight: '1.25',

  colorBg: '#ffffff',
  colorBgActive: '#e9edf2',
  colorFg: '#a4abb3',
  colorFgHeading: '#2a2a2a',
  colorFgText: '#4b4b4b',
  colorFgHighlight: '#40dc7e',

  separator: '#ebeef2',

  colorGray: 'rgba(81, 113, 165, 0.15)',
  colorNeutral: 'transparent',
  colorWhite: '#ffffff',

  disabled: 'rgba(255, 255, 255, 0.4)',
  primary: '#8a7fff',
  success: '#40dc7e',
  info: '#4ca6ff',
  warning: '#ffa100',
  danger: '#ff4c6a',

  socialColorFacebook: '#3b5998',
  socialColorTwitter: '#55acee',
  socialColorGoogle: '#dd4b39',
  socialColorLinkedin: '#0177b5',
  socialColorGithub: '#6b6b6b',
  socialColorStackoverflow: '#2f96e8',
  socialColorDribble: '#f26798',
  socialColorBehance: '#0093fa',

  borderColor: 'rgba(81, 113, 165, 0.15)',
  shadow: '0 2px 12px 0 #dfe3eb',

  linkColor: '#3dcc6d',
  linkColorHover: '#2ee56b',
  linkColorVisited: '#3dcc6d',

  scrollbarFg: '#dadada',
  scrollbarBg: '#f2f2f2',
  scrollbarWidth: '5px',
  scrollbarThumbRadius: '2.5px',

  radialGradient: 'none',
  linearGradient: 'none',

  layoutFontFamily: 'fontMain',
  layoutFontSize: 'fontSize',
  layoutLineHeight: 'lineHeight',
  layoutFg: 'colorFg',
  layoutBg: '#ebeff5',
  layoutMinHeight: '100vh',
  layoutContentWidth: '900px',
  layoutWindowModeMinWidth: '300px',
  layoutWindowModeMaxWidth: '1920px',
  layoutWindowModeBg: 'layoutBg',
  layoutWindowModePaddingTop: '4.75rem',
  layoutWindowShadow: 'shadow',
  layoutPadding: '2.25rem 2.25rem 0.75rem',
  layoutMediumPadding: '1.5rem 1.5rem 0.5rem',
  layoutSmallPadding: '1rem 1rem 0',

  cardFontSize: 'fontSize',
  cardLineHeight: 'lineHeight',
  cardFontWeight: 'fontWeightNormal',
  cardFg: 'colorFg',
  cardFgText: 'colorFgText',
  cardFgHeading: 'colorFgHeading',
  cardBg: 'colorBg',
  cardHeightXXS: '96px',
  cardHeightXS: '216px',
  cardHeightS: '336px',
  cardHeightM: '456px',
  cardHeightL: '576px',
  cardHeightXL: '696px',
  cardHeightXXL: '816px',
  cardShadow: 'shadow',
  cardBorderWidth: 0,
  cardBorderType: 'solid',
  cardBorderColor: 'colorBg',
  cardBorderRadius: 'radius',
  cardPadding: 'padding',
  cardMargin: 'margin',
  cardHeaderFontFamily: 'fontSecondary',
  cardHeaderFontSize: 'fontSizeLg',
  cardHeaderFontWeight: 'fontWeightBold',
  cardSeparator: 'separator',
  cardHeaderFg: 'colorFg',
  cardHeaderFgHeading: 'colorFgHeading',
  cardHeaderActiveBg: 'colorFg',
  cardHeaderActiveFg: 'colorBg',
  cardHeaderDisabledBg: 'disabled',
  cardHeaderPrimaryBg: 'primary',
  cardHeaderInfoBg: 'info',
  cardHeaderSuccessBg: 'success',
  cardHeaderWarningBg: 'warning',
  cardHeaderDangerBg: 'danger',
  cardHeaderBorderWidth: '1px',
  cardHeaderBorderType: 'solid',
  cardHeaderBorderColor: 'cardSeparator',

  headerHeight: '4.75rem',
  headerPadding: '1.25rem',
  headerFontFamily: 'fontSecondary',
  headerFontSize: 'fontSize',
  headerLineHeight: 'lineHeight',
  headerFg: 'colorFgHeading',
  headerBg: 'colorBg',
  headerShadow: 'shadow',

  footerHeight: '4.725rem',
  footerPadding: '1.25rem',
  footerFg: 'colorFgHeading',
  footerFgHighlight: 'colorFgHeading',
  footerBg: 'colorBg',
  footerSeparator: 'separator',
  footerShadow: 'shadow',

  sidebarFontSize: 'fontSize',
  sidebarLineHeight: 'lineHeight',
  sidebarFg: 'colorFgHeading',
  sidebarBg: 'colorBg',
  sidebarHeight: '100vh',
  sidebarWidth: '16rem',
  sidebarWidthCompact: '3.5rem',
  sidebarPadding: 'padding',
  sidebarHeaderHeight: '3.5rem',
  sidebarFooterHeight: '3.5rem',
  sidebarShadow: 'shadow',

  menuFontFamily: 'fontSecondary',
  menuFontSize: 'fontSize',
  menuFontWeight: 'fontWeightBorder',
  menuFg: 'colorFgText',
  menuBg: 'colorBg',
  menuActiveFg: 'colorFgHeading',
  menuActiveBg: 'colorBg',
  menuActiveFontWeight: 'fontWeightBold',
  menuSubmenuBg: 'colorBg',
  menuSubmenuFg: 'colorFgText',
  menuSubmenuActiveFg: 'colorFgHeading',
  menuSubmenuActiveBg: 'colorBg',
  menuSubmenuActiveBorderColor: 'colorFgHighlight',
  menuSubmenuActiveShadow: 'none',
  menuSubmenuHoverFg: 'colorFgHeading',
  menuSubmenuHoverBg: 'colorBg',
  menuSubmenuItemBorderWidth: '0.125rem',
  menuSubmenuItemBorderRadius: 'radius',
  menuSubmenuItemPadding: '0.5rem 1rem',
  menuSubmenuItemContainerPadding: '0 1.25rem',
  menuSubmenuPadding: '0.5rem',
  menuGroupFontWeight: 'fontWeightBorder',
  menuGroupFontSize: '0.875rem',
  menuGroupFg: 'colorFg',
  menuGroupPadding: '1rem 1.25rem',
  menuItemPadding: '0.675rem 0.75rem',
  menuItemSeparator: 'separator',
  menuIconFontSize: '1.5rem',
  menuIconMargin: '0 0.25rem 0',
  menuIconColor: 'colorFg',
  menuIconActiveColor: 'colorFgHeading',

  tabsFontFamily: 'fontSecondary',
  tabsFontSize: 'fontSizeLg',
  tabsContentFontFamily: 'fontMain',
  tabsContentFontSize: 'fontSize',
  tabsActiveBg: 'transparent',
  tabsActiveFontWeight: 'fontWeightBold',
  tabsPadding: 'padding',
  tabsContentPadding: 'padding',
  tabsHeaderBg: 'transparent',
  tabsSeparator: 'separator',
  tabsFg: 'colorFg',
  tabsFgText: 'colorFgText',
  tabsFgHeading: 'colorFgHeading',
  tabsBg: 'transparent',
  tabsSelected: 'success',
  tabsSelectedSecondColor: 'success',
  tabsSelectedDegrees: 0,
  tabsIconOnlyMaxWidth: '576px',

  routeTabsFontFamily: 'fontSecondary',
  routeTabsFontSize: 'fontSizeLg',
  routeTabsActiveBg: 'transparent',
  routeTabsActiveFontWeight: 'fontWeightBold',
  routeTabsPadding: 'padding',
  routeTabsHeaderBg: 'transparent',
  routeTabsSeparator: 'separator',
  routeTabsFg: 'colorFg',
  routeTabsFgHeading: 'colorFgHeading',
  routeTabsBg: 'transparent',
  routeTabsSelected: 'success',
  routeTabsIconOnlyMaxWidth: '576px',

  userFontSize: 'fontSize',
  userLineHeight: 'lineHeight',
  userBg: 'colorBg',
  userFg: 'colorFg',
  userFgHighlight: '#bcc3cc',
  userFontFamilySecondary: 'fontSecondary',
  userSizeSmall: '1.5rem',
  userSizeMedium: '2.5rem',
  userSizeLarge: '3.25rem',
  userSizeXlarge: '4rem',

  popoverFg: 'colorFgHeading',
  popoverBg: 'colorBg',
  popoverBorder: 'success',
  popoverBorderRadius: 'radius',
  popoverShadow: 'none',
  popoverArrowSize: '11px',

  contextMenuFg: 'colorFgHeading',
  contextMenuBg: 'colorBg',
  contextMenuActiveFg: 'colorWhite',
  contextMenuActiveBg: 'success',
  contextMenuBorder: 'colorSuccess',
  contextMenuBorderRadius: 'radius',
  contextMenuShadow: 'none',
  contextMenuArrowSize: '11px',

  actionsFontSize: 'fontSize',
  actionsFontFamily: 'fontSecondary',
  actionsLineHeight: 'lineHeight',
  actionsFg: 'colorFg',
  actionsBg: 'colorBg',
  actionsSeparator: 'separator',
  actionsPadding: 'padding',
  actionsSizeSmall: '1.5rem',
  actionsSizeMedium: '2.25rem',
  actionsSizeLarge: '3.5rem',

  searchBtnOpenFg: 'colorFg',
  searchBtnCloseFg: 'colorFg',
  searchBg: 'layoutBg',
  searchBgSecondary: 'colorFg',
  searchText: 'colorFgHeading',
  searchInfo: 'colorFg',
  searchDash: 'colorFg',
  searchPlaceholder: 'colorFg',

  smartTableHeaderFontFamily: 'fontSecondary',
  smartTableHeaderFontSize: 'fontSize',
  smartTableHeaderFontWeight: 'fontWeightBold',
  smartTableHeaderLineHeight: 'lineHeight',
  smartTableHeaderFg: 'colorFgHeading',
  smartTableHeaderBg: 'colorBg',
  smartTableFontFamily: 'fontMain',
  smartTableFontSize: 'fontSize',
  smartTableFontWeight: 'fontWeightNormal',
  smartTableLineHeight: 'lineHeight',
  smartTableFg: 'colorFgHeading',
  smartTableBg: 'colorBg',
  smartTableBgEven: '#f5f7fc',
  smartTableFgSecondary: 'colorFg',
  smartTableBgActive: '#e6f3ff',
  smartTablePadding: '0.875rem 1.25rem',
  smartTableFilterPadding: '0.375rem 0.5rem',
  smartTableSeparator: 'separator',
  smartTableBorderRadius: 'radius',
  smartTablePagingBorderColor: 'separator',
  smartTablePagingBorderWidth: '1px',
  smartTablePagingFgActive: '#ffffff',
  smartTablePagingBgActive: 'success',
  smartTablePagingHover: 'rgba(0, 0, 0, 0.05)',

  toasterBg: 'primary',
  toasterFgDefault: 'colorInverse',
  toasterBtnCloseBg: 'transparent',
  toasterBtnCloseFg: 'toasterFgDefault',
  toasterShadow: 'shadow',
  toasterFg: 'colorWhite',
  toasterSuccess: 'success',
  toasterInfo: 'info',
  toasterWarning: 'warning',
  toasterWait: 'primary',
  toasterError: 'danger',

  btnFg: 'colorWhite',
  btnFontFamily: 'fontSecondary',
  btnLineHeight: 'lineHeight',
  btnDisabledOpacity: 0.3,
  btnCursor: 'default',
  btnPrimaryBg: 'primary',
  btnSecondaryBg: 'transparent',
  btnInfoBg: 'info',
  btnSuccessBg: 'success',
  btnWarningBg: 'warning',
  btnDangerBg: 'danger',
  btnSecondaryBorder: '#dadfe6',
  btnSecondaryBorderWidth: '2px',
  btnPaddingYLg: '0.875rem',
  btnPaddingXLg: '1.75rem',
  btnFontSizeLg: 'fontSizeLg',
  btnPaddingXMd: '1.5rem',
  btnFontSizeMd: '1rem',
  btnPaddingYSm: '0.625rem',
  btnPaddingXSm: '1.5rem',
  btnFontSizeSm: '0.875rem',
  btnPaddingYXs: '0.5rem',
  btnPaddingXXs: '1.25rem',
  btnFontSizeXs: '0.75rem',
  btnBorderRadius: 'radius',
  btnRectangleBorderRadius: '0.25rem',
  btnSemiRoundBorderRadius: '0.75rem',
  btnRoundBorderRadius: '1.5rem',

  btnHeroShadow: 'none',
  btnHeroTextShadow: 'none',
  btnHeroBevelSize: '0 0 0 0',
  btnHeroGlowSize: '0 0 0 0',
  btnHeroPrimaryGlowSize: 'btnHeroGlowSize',
  btnHeroSuccessGlowSize: 'btnHeroGlowSize',
  btnHeroWarningGlowSize: 'btnHeroGlowSize',
  btnHeroInfoGlowSize: 'btnHeroGlowSize',
  btnHeroDangerGlowSize: 'btnHeroGlowSize',
  btnHeroSecondaryGlowSize: 'btnHeroGlowSize',
  btnHeroDegree: '20deg',
  btnHeroPrimaryDegree: 'btnHeroDegree',
  btnHeroSuccessDegree: 'btnHeroDegree',
  btnHeroWarningDegree: '10deg',
  btnHeroInfoDegree: '10deg',
  btnHeroDangerDegree: '20deg',
  btnHeroSecondaryDegree: 'btnHeroDegree',
  btnHeroBorderRadius: 'radius',
  btnOutlineFg: 'colorFgHeading',
  btnOutlineHoverFg: '#ffffff',
  btnOutlineFocusFg: 'colorFgHeading',
  btnGroupBg: 'layoutBg',
  btnGroupFg: 'colorFgHeading',
  btnGroupSeparator: '#dadfe6',

  formControlTextPrimaryColor: 'colorFgHeading',
  formControlBg: 'colorBg',
  formControlFocusBg: 'colorBg',
  formControlBorderWidth: '2px',
  formControlBorderType: 'solid',
  formControlBorderColor: '#dadfe6',
  formControlRectangleBorderRadius: 'radius',
  formControlSemiRoundBorderRadius: '0.75rem',
  formControlRoundBorderRadius: '1.5rem',
  formControlSelectedBorderColor: 'success',
  formControlInfoBorderColor: 'info',
  formControlSuccessBorderColor: 'success',
  formControlDangerBorderColor: 'danger',
  formControlWarningBorderColor: 'warning',
  formControlPlaceholderColor: 'colorFg',
  formControlPlaceholderFontSize: '1rem',
  formControlFontSizeMd: '1rem',
  formControlPaddingMd: '0.75rem 1.125rem',
  formControlFontSizeSm: 'fontSizeSm',
  formControlPaddingSm: '0.375rem 1.125rem',
  formControlFontSizeLg: 'fontSizeLg',
  formControlPaddingLg: '1.125rem 1.125rem',
  formControlLabelFontWeight: 400,
  formControlFeedbackFontSize: '0.875rem',
  formControlFeedbackFontWeight: 'fontWeightNormal',

  checkboxBg: 'transparent',
  checkboxSize: '1.25rem',
  checkboxBorderSize: '2px',
  checkboxBorderColor: 'formControlBorderColor',
  checkboxCheckMark: 'transparent',
  checkboxCheckedBg: 'transparent',
  checkboxCheckedSize: '1.25rem',
  checkboxCheckedBorderSize: '2px',
  checkboxCheckedBorderColor: 'success',
  checkboxCheckedCheckMark: 'colorFgHeading',
  checkboxDisabledBg: 'transparent',
  checkboxDisabledSize: '1.25rem',
  checkboxDisabledBorderSize: '2px',
  checkboxDisabledBorderColor: 'colorFgHeading',
  checkboxDisabledCheckMark: 'colorFgHeading',

  modalFontSize: 'fontSize',
  modalLineHeight: 'lineHeight',
  modalFontWeight: 'fontWeightNormal',
  modalFg: 'colorFgText',
  modalFgHeading: 'colorFgHeading',
  modalBg: 'colorBg',
  modalBorder: 'transparent',
  modalBorderRadius: 'radius',
  modalPadding: 'padding',
  modalHeaderFontFamily: 'fontSecondary',
  modalHeaderFontWeight: 'fontWeightBorder',
  modalHeaderFontSize: 'fontSizeLg',
  modalBodyFontFamily: 'fontMain',
  modalBodyFontWeight: 'fontWeightNormal',
  modalBodyFontSize: 'fontSize',
  modalSeparator: 'separator',

  badgeFgText: 'colorWhite',
  badgePrimaryBgColor: 'primary',
  badgeSuccessBgColor: 'success',
  badgeInfoBgColor: 'info',
  badgeWarningBgColor: 'warning',
  badgeDangerBgColor: 'danger',

  progressBarHeightXlg: '1.75rem',
  progressBarHeightLg: '1.5rem',
  progressBarHeight: '1.375rem',
  progressBarHeightSm: '1.25rem',
  progressBarHeightXs: '1rem',
  progressBarAnimationDuration: '400ms',
  progressBarFontSizeXlg: 'fontSizeXlg',
  progressBarFontSizeLg: 'fontSizeLg',
  progressBarFontSize: 'fontSize',
  progressBarFontSizeSm: 'fontSizeSm',
  progressBarFontSizeXs: 'fontSizeXs',
  progressBarRadius: 'radius',
  progressBarBg: 'layoutBg',
  progressBarFontColor: 'colorWhite',
  progressBarFontWeight: 'fontWeightBold',
  progressBarDefaultBg: 'info',
  progressBarPrimaryBg: 'primary',
  progressBarSuccessBg: 'success',
  progressBarInfoBg: 'info',
  progressBarWarningBg: 'warning',
  progressBarDangerBg: 'danger',

  alertFontSize: 'fontSize',
  alertLineHeight: 'lineHeight',
  alertFontWeight: 'fontWeightNormal',
  alertFg: 'colorWhite',
  alertOutlineFg: 'colorFg',
  alertBg: 'colorBg',
  alertActiveBg: 'colorFg',
  alertDisabledBg: 'disabled',
  alertDisabledFg: 'colorFg',
  alertPrimaryBg: 'primary',
  alertInfoBg: 'info',
  alertSuccessBg: 'success',
  alertWarningBg: 'warning',
  alertDangerBg: 'danger',
  alertHeightXxsmall: '52px',
  alertHeightXsmall: '72px',
  alertHeightSmall: '92px',
  alertHeightMedium: '112px',
  alertHeightLarge: '132px',
  alertHeightXlarge: '152px',
  alertHeightXxlarge: '172px',
  alertShadow: 'none',
  alertBorderRadius: 'radius',
  alertPadding: '1rem 1.125rem',
  alertClosablePadding: '3rem',
  alertButtonPadding: '3rem',
  alertMargin: 'margin',

  chatFontSize: 'fontSize',
  chatFg: 'colorWhite',
  chatBg: 'colorBg',
  chatBorderRadius: 'radius',
  chatFgText: 'colorFgText',
  chatHeightXxsmall: '96px',
  chatHeightXsmall: '216px',
  chatHeightSmall: '336px',
  chatHeightMedium: '456px',
  chatHeightLarge: '576px',
  chatHeightXlarge: '696px',
  chatHeightXxlarge: '816px',
  chatBorder: 'border',
  chatPadding: 'padding',
  chatShadow: 'shadow',
  chatSeparator: 'separator',
  chatMessageFg: 'colorWhite',
  chatMessageBg: 'linearGradient(to right, #4ca6ff, #59bfff)',
  chatMessageReplyBg: 'colorBgActive',
  chatMessageReplyFg: 'colorFgText',
  chatMessageAvatarBg: 'colorFg',
  chatMessageSenderFg: 'colorFg',
  chatMessageQuoteFg: 'colorFg',
  chatMessageQuoteBg: 'colorBgActive',
  chatMessageFileFg: 'colorFg',
  chatMessageFileBg: 'transparent',
  chatFormBg: 'transparent',
  chatFormFg: 'colorFgHeading',
  chatFormBorder: 'separator',
  chatFormPlaceholderFg: 'colorFg',
  chatFormActiveBorder: 'colorFg',
  chatActiveBg: 'colorFg',
  chatDisabledBg: 'disabled',
  chatDisabledFg: 'colorFg',
  chatPrimaryBg: 'primary',
  chatInfoBg: 'info',
  chatSuccessBg: 'success',
  chatWarningBg: 'warning',
  chatDangerBg: 'danger',

  spinnerBg: 'rgba(255, 255, 255, 0.83)',
  spinnerCircleBg: 'colorBgActive',
  spinnerFg: 'colorFgText',
  spinnerActiveBg: 'colorFg',
  spinnerDisabledBg: 'disabled',
  spinnerDisabledFg: 'colorFg',
  spinnerPrimaryBg: 'primary',
  spinnerInfoBg: 'info',
  spinnerSuccessBg: 'success',
  spinnerWarningBg: 'warning',
  spinnerDangerBg: 'danger',
  spinnerXxsmall: '1.25rem',
  spinnerXsmall: '1.5rem',
  spinnerSmall: '1.75rem',
  spinnerMedium: '2rem',
  spinnerLarge: '2.25rem',
  spinnerXlarge: '2.5rem',
  spinnerXxlarge: '3rem',

  stepperIndexSize: '2rem',
  stepperLabelFontSize: 'fontSizeSm',
  stepperLabelFontWeight: 'fontWeightBorder',
  stepperAccentColor: 'primary',
  stepperCompletedFg: 'colorWhite',
  stepperFg: 'colorFg',
  stepperCompletedIconSize: '1.5rem',
  stepperCompletedIconWeight: 'fontWeightUltraBold',
  stepperStepPadding: 'padding',

  accordionPadding: 'padding',
  accordionSeparator: 'separator',
  accordionHeaderFontFamily: 'fontSecondary',
  accordionHeaderFontSize: 'fontSizeLg',
  accordionHeaderFontWeight: 'fontWeightNormal',
  accordionHeaderFgHeading: 'colorFgHeading',
  accordionHeaderDisabledFg: 'colorFg',
  accordionHeaderBorderWidth: '1px',
  accordionHeaderBorderType: 'solid',
  accordionHeaderBorderColor: 'accordionSeparator',
  accordionBorderRadius: 'radius',
  accordionItemBg: 'colorBg',
  accordionItemFontSize: 'fontSize',
  accordionItemFontWeight: 'fontWeightNormal',
  accordionItemFontFamily: 'fontMain',
  accordionItemFgText: 'colorFgText',
  accordionItemShadow: 'shadow',

  listItemBorderColor: 'separator',
  listItemPadding: '1rem',

  calendarWidth: '21.875rem',
  calendarBodyHeight: '25.625rem',
  calendarHeaderTitleFontSize: 'fontSizeXlg',
  calendarHeaderTitleFontWeight: 'fontWeightBold',
  calendarHeaderSubTitleFontSize: 'fontSize',
  calendarHeaderSubTitleFontWeight: 'fontWeightThin',
  calendarNavigationButtonWidth: '10rem',
  calendarSelectedItemBg: 'success',
  calendarHoverItemBg: 'success',
  calendarTodayItemBg: 'colorBgActive',
  calendarActiveItemBg: 'success',
  calendarFg: 'colorFgText',
  calendarSelectedFg: 'colorWhite',
  calendarTodayFg: 'calendarFg',
  calendarDayCellWidth: '2.625rem',
  calendarDayCellHeight: '2.625rem',
  calendarMonthCellWidth: '4.25rem',
  calendarMonthCellHeight: '2.375rem',
  calendarYearCellWidth: 'calendarMonthCellWidth',
  calendarYearCellHeight: 'calendarMonthCellHeight',
  calendarInactiveOpacity: 0.5,
  calendarDisabledOpacity: 0.3,
  calendarBorderRadius: 'radius',
  calendarWeekdayWidth: 'calendarDayCellWidth',
  calendarWeekdayHeight: '1.75rem',
  calendarWeekdayFontSize: 'fontSizeXs',
  calendarWeekdayFontWeight: 'fontWeightNormal',
  calendarWeekdayFg: 'colorFg',
  calendarWeekdayHolidayFg: 'danger',
  calendarRangeBgInRange: '#ebfbf2',
  calendarLargeWidth: '24.375rem',
  calendarLargeBodyHeight: '27.75rem',
  calendarDayCellLargeWidth: '3rem',
  calendarDayCellLargeHeight: '3rem',
  calendarMonthCellLargeWidth: '4.25rem',
  calendarMonthCellLargeHeight: '2.375rem',
  calendarYearCellLargeWidth: 'calendarMonthCellWidth',
  calendarYearCellLargeHeight: 'calendarMonthCellHeight',
  overlayBackdropBg: 'rgba(0, 0, 0, 0.288)',
  tooltipBg: 'colorFgText',
  tooltipPrimaryBg: 'primary',
  tooltipInfoBg: 'info',
  tooltipSuccessBg: 'success',
  tooltipWarningBg: 'warning',
  tooltipDangerBg: 'danger',
  tooltipFg: 'colorBgActive',
  tooltipStatusFg: 'colorBgActive',
  tooltipShadow: 'shadow',
  tooltipFontSize: 'fontSize',

  selectBorderWidth: '2px',
  selectMaxHeight: '20rem',
  selectBg: 'colorBg',
  selectCheckboxColor: 'checkboxBorderColor',
  selectCheckmarkColor: 'checkboxBorderColor',
  selectOptionDisabledBg: '#f2f4f7',
  selectOptionDisabledOpacity: '0.3',
  selectOptionPadding: '0.75rem 1.5rem',

  datePickerFg: 'colorFgHeading',
  datePickerBg: 'colorBg',
  datePickerBorder: 'success',
  datePickerBorderRadius: 'radius',
  datePickerShadow: 'none',
  datePickerArrowSize: '11px',

  radioBg: 'transparent',
  radioFg: 'colorFgText',
  radioSize: '1.25rem',
  radioBorderSize: '2px',
  radioBorderColor: 'formControlBorderColor',
  radioCheckmark: 'transparent',
  radioCheckedBg: 'transparent',
  radioCheckedSize: '1.25rem',
  radioCheckedBorderSize: '2px',
  radioCheckedBorderColor: 'success',
  radioCheckedCheckmark: 'success',
  radioDisabledBg: 'transparent',
  radioDisabledSize: '1.25rem',
  radioDisabledBorderSize: '2px',
  radioDisabledBorderColor: 'radioBorderColor',
  radioDisabledCheckmark: 'radioCheckmark'
};
