/*
 * @license
 * Copyright Ahmed Elywa. All Rights Reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */

export default {
	colorPrimary100: '#f2f6ff',
	colorPrimary200: '#d9e4ff',
	colorPrimary300: '#a6c1ff',
	colorPrimary400: '#598bff',
	colorPrimary500: '#3366ff',
	colorPrimary600: '#274bdb',
	colorPrimary700: '#1a34b8',
	colorPrimary800: '#102694',
	colorPrimary900: '#091c7a',

	colorPrimaryTransparent100: 'rgba(51, 102, 255, 0.08)',
	colorPrimaryTransparent200: 'rgba(51, 102, 255, 0.16)',
	colorPrimaryTransparent300: 'rgba(51, 102, 255, 0.24)',
	colorPrimaryTransparent400: 'rgba(51, 102, 255, 0.32)',
	colorPrimaryTransparent500: 'rgba(51, 102, 255, 0.4)',
	colorPrimaryTransparent600: 'rgba(51, 102, 255, 0.48)',

	colorSuccess100: '#f0fff5',
	colorSuccess200: '#ccfce3',
	colorSuccess300: '#8cfac7',
	colorSuccess400: '#2ce69b',
	colorSuccess500: '#00d68f',
	colorSuccess600: '#00b887',
	colorSuccess700: '#00997a',
	colorSuccess800: '#007d6c',
	colorSuccess900: '#004a45',

	colorSuccessTransparent100: 'rgba(0, 214, 143, 0.08)',
	colorSuccessTransparent200: 'rgba(0, 214, 143, 0.16)',
	colorSuccessTransparent300: 'rgba(0, 214, 143, 0.24)',
	colorSuccessTransparent400: 'rgba(0, 214, 143, 0.32)',
	colorSuccessTransparent500: 'rgba(0, 214, 143, 0.4)',
	colorSuccessTransparent600: 'rgba(0, 214, 143, 0.48)',

	colorInfo100: '#f2f8ff',
	colorInfo200: '#c7e2ff',
	colorInfo300: '#94cbff',
	colorInfo400: '#42aaff',
	colorInfo500: '#0095ff',
	colorInfo600: '#006fd6',
	colorInfo700: '#0057c2',
	colorInfo800: '#0041a8',
	colorInfo900: '#002885',

	colorInfoTransparent100: 'rgba(0, 149, 255, 0.08)',
	colorInfoTransparent200: 'rgba(0, 149, 255, 0.16)',
	colorInfoTransparent300: 'rgba(0, 149, 255, 0.24)',
	colorInfoTransparent400: 'rgba(0, 149, 255, 0.32)',
	colorInfoTransparent500: 'rgba(0, 149, 255, 0.4)',
	colorInfoTransparent600: 'rgba(0, 149, 255, 0.48)',

	colorWarning100: '#fffdf2',
	colorWarning200: '#fff1c2',
	colorWarning300: '#ffe59e',
	colorWarning400: '#ffc94d',
	colorWarning500: '#ffaa00',
	colorWarning600: '#db8b00',
	colorWarning700: '#b86e00',
	colorWarning800: '#945400',
	colorWarning900: '#703c00',

	colorWarningTransparent100: 'rgba(255, 170, 0, 0.08)',
	colorWarningTransparent200: 'rgba(255, 170, 0, 0.16)',
	colorWarningTransparent300: 'rgba(255, 170, 0, 0.24)',
	colorWarningTransparent400: 'rgba(255, 170, 0, 0.32)',
	colorWarningTransparent500: 'rgba(255, 170, 0, 0.4)',
	colorWarningTransparent600: 'rgba(255, 170, 0, 0.48)',

	colorDanger100: '#fff2f2',
	colorDanger200: '#ffd6d9',
	colorDanger300: '#ffa8b4',
	colorDanger400: '#ff708d',
	colorDanger500: '#ff3d71',
	colorDanger600: '#db2c66',
	colorDanger700: '#b81d5b',
	colorDanger800: '#94124e',
	colorDanger900: '#700940',

	colorDangerTransparent100: 'rgba(255, 61, 113, 0.08)',
	colorDangerTransparent200: 'rgba(255, 61, 113, 0.16)',
	colorDangerTransparent300: 'rgba(255, 61, 113, 0.24)',
	colorDangerTransparent400: 'rgba(255, 61, 113, 0.32)',
	colorDangerTransparent500: 'rgba(255, 61, 113, 0.4)',
	colorDangerTransparent600: 'rgba(255, 61, 113, 0.48)',

	/* Basic colors - for backgrounds and borders and texts */

	colorBasic100: '#ffffff',
	colorBasic200: '#f7f9fc',
	colorBasic300: '#edf1f7',
	colorBasic400: '#e4e9f2',
	colorBasic500: '#c5cee0',
	colorBasic600: '#8f9bb3',
	colorBasic700: '#2e3a59',
	colorBasic800: '#222b45',
	colorBasic900: '#192038',
	colorBasic1000: '#151a30',
	colorBasic1100: '#101426',

	colorBasicTransparent100: 'rgba(143, 155, 179, 0.08)',
	colorBasicTransparent200: 'rgba(143, 155, 179, 0.16)',
	colorBasicTransparent300: 'rgba(143, 155, 179, 0.24)',
	colorBasicTransparent400: 'rgba(143, 155, 179, 0.32)',
	colorBasicTransparent500: 'rgba(143, 155, 179, 0.4)',
	colorBasicTransparent600: 'rgba(143, 155, 179, 0.48)',

	colorBasicControlTransparent100: 'rgba(255, 255, 255, 0.08)',
	colorBasicControlTransparent200: 'rgba(255, 255, 255, 0.16)',
	colorBasicControlTransparent300: 'rgba(255, 255, 255, 0.24)',
	colorBasicControlTransparent400: 'rgba(255, 255, 255, 0.32)',
	colorBasicControlTransparent500: 'rgba(255, 255, 255, 0.4)',
	colorBasicControlTransparent600: 'rgba(255, 255, 255, 0.48)',

	/* Status colors states - focus, hover, default, active, disabled  */

	colorBasicFocus: 'colorBasic400',
	colorBasicHover: 'colorBasic200',
	colorBasicDefault: 'colorBasic300',
	colorBasicActive: 'colorBasic400',
	colorBasicDisabled: 'colorBasicTransparent300',
	colorBasicFocusBorder: 'colorBasic500',
	colorBasicHoverBorder: 'colorBasicHover',
	colorBasicDefaultBorder: 'colorBasicDefault',
	colorBasicActiveBorder: 'colorBasicActive',
	colorBasicDisabledBorder: 'colorBasicDisabled',

	colorBasicTransparentFocus: 'colorBasicTransparent300',
	colorBasicTransparentHover: 'colorBasicTransparent200',
	colorBasicTransparentDefault: 'colorBasicTransparent100',
	colorBasicTransparentActive: 'colorBasicTransparent300',
	colorBasicTransparentDisabled: 'colorBasicTransparent200',
	colorBasicTransparentFocusBorder: 'colorBasic600',
	colorBasicTransparentHoverBorder: 'colorBasic600',
	colorBasicTransparentDefaultBorder: 'colorBasic600',
	colorBasicTransparentActiveBorder: 'colorBasic600',
	colorBasicTransparentDisabledBorder: 'colorBasicTransparent300',

	colorPrimaryFocus: 'colorPrimary600',
	colorPrimaryHover: 'colorPrimary400',
	colorPrimaryDefault: 'colorPrimary500',
	colorPrimaryActive: 'colorPrimary600',
	colorPrimaryDisabled: 'colorBasicTransparent300',
	colorPrimaryFocusBorder: 'colorPrimary700',
	colorPrimaryHoverBorder: 'colorPrimaryHover',
	colorPrimaryDefaultBorder: 'colorPrimaryDefault',
	colorPrimaryActiveBorder: 'colorPrimaryActive',
	colorPrimaryDisabledBorder: 'colorPrimaryDisabled',

	colorPrimaryTransparentFocus: 'colorPrimaryTransparent300',
	colorPrimaryTransparentHover: 'colorPrimaryTransparent200',
	colorPrimaryTransparentDefault: 'colorPrimaryTransparent100',
	colorPrimaryTransparentActive: 'colorPrimaryTransparent300',
	colorPrimaryTransparentDisabled: 'colorBasicTransparent200',
	colorPrimaryTransparentFocusBorder: 'colorPrimary500',
	colorPrimaryTransparentHoverBorder: 'colorPrimary500',
	colorPrimaryTransparentDefaultBorder: 'colorPrimary500',
	colorPrimaryTransparentActiveBorder: 'colorPrimary500',
	colorPrimaryTransparentDisabledBorder: 'colorBasicTransparent300',

	colorSuccessFocus: 'colorSuccess600',
	colorSuccessHover: 'colorSuccess400',
	colorSuccessDefault: 'colorSuccess500',
	colorSuccessActive: 'colorSuccess600',
	colorSuccessDisabled: 'colorBasicTransparent300',
	colorSuccessFocusBorder: 'colorSuccess700',
	colorSuccessHoverBorder: 'colorSuccessHover',
	colorSuccessDefaultBorder: 'colorSuccessDefault',
	colorSuccessActiveBorder: 'colorSuccessActive',
	colorSuccessDisabledBorder: 'colorSuccessDisabled',

	colorSuccessTransparentFocus: 'colorSuccessTransparent300',
	colorSuccessTransparentFocusBorder: 'colorSuccess500',
	colorSuccessTransparentHover: 'colorSuccessTransparent200',
	colorSuccessTransparentHoverBorder: 'colorSuccess500',
	colorSuccessTransparentDefault: 'colorSuccessTransparent100',
	colorSuccessTransparentDefaultBorder: 'colorSuccess500',
	colorSuccessTransparentActive: 'colorSuccessTransparent300',
	colorSuccessTransparentActiveBorder: 'colorSuccess500',
	colorSuccessTransparentDisabled: 'colorBasicTransparent200',
	colorSuccessTransparentDisabledBorder: 'colorBasicTransparent300',

	colorInfoFocus: 'colorInfo600',
	colorInfoHover: 'colorInfo400',
	colorInfoDefault: 'colorInfo500',
	colorInfoActive: 'colorInfo600',
	colorInfoDisabled: 'colorBasicTransparent300',
	colorInfoFocusBorder: 'colorInfo700',
	colorInfoHoverBorder: 'colorInfoHover',
	colorInfoDefaultBorder: 'colorInfoDefault',
	colorInfoActiveBorder: 'colorInfoActive',
	colorInfoDisabledBorder: 'colorInfoDisabled',

	colorInfoTransparentFocus: 'colorInfoTransparent300',
	colorInfoTransparentHover: 'colorInfoTransparent200',
	colorInfoTransparentDefault: 'colorInfoTransparent100',
	colorInfoTransparentActive: 'colorInfoTransparent300',
	colorInfoTransparentDisabled: 'colorBasicTransparent200',
	colorInfoTransparentFocusBorder: 'colorInfo500',
	colorInfoTransparentHoverBorder: 'colorInfo500',
	colorInfoTransparentDefaultBorder: 'colorInfo500',
	colorInfoTransparentActiveBorder: 'colorInfo500',
	colorInfoTransparentDisabledBorder: 'colorBasicTransparent300',

	colorWarningFocus: 'colorWarning600',
	colorWarningHover: 'colorWarning400',
	colorWarningDefault: 'colorWarning500',
	colorWarningActive: 'colorWarning600',
	colorWarningDisabled: 'colorBasicTransparent300',
	colorWarningFocusBorder: 'colorWarning700',
	colorWarningHoverBorder: 'colorWarningHover',
	colorWarningDefaultBorder: 'colorWarningDefault',
	colorWarningActiveBorder: 'colorWarningActive',
	colorWarningDisabledBorder: 'colorWarningDisabled',

	colorWarningTransparentFocus: 'colorWarningTransparent300',
	colorWarningTransparentHover: 'colorWarningTransparent200',
	colorWarningTransparentDefault: 'colorWarningTransparent100',
	colorWarningTransparentActive: 'colorWarningTransparent300',
	colorWarningTransparentDisabled: 'colorBasicTransparent200',
	colorWarningTransparentFocusBorder: 'colorWarning500',
	colorWarningTransparentHoverBorder: 'colorWarning500',
	colorWarningTransparentDefaultBorder: 'colorWarning500',
	colorWarningTransparentActiveBorder: 'colorWarning500',
	colorWarningTransparentDisabledBorder: 'colorBasicTransparent300',

	colorDangerFocus: 'colorDanger600',
	colorDangerHover: 'colorDanger400',
	colorDangerDefault: 'colorDanger500',
	colorDangerActive: 'colorDanger600',
	colorDangerDisabled: 'colorBasicTransparent300',
	colorDangerFocusBorder: 'colorDanger700',
	colorDangerHoverBorder: 'colorDangerHover',
	colorDangerDefaultBorder: 'colorDangerDefault',
	colorDangerActiveBorder: 'colorDangerActive',
	colorDangerDisabledBorder: 'colorDangerDisabled',

	colorDangerTransparentFocus: 'colorDangerTransparent300',
	colorDangerTransparentHover: 'colorDangerTransparent200',
	colorDangerTransparentDefault: 'colorDangerTransparent100',
	colorDangerTransparentActive: 'colorDangerTransparent300',
	colorDangerTransparentDisabled: 'colorBasicTransparent200',
	colorDangerTransparentFocusBorder: 'colorDanger500',
	colorDangerTransparentHoverBorder: 'colorDanger500',
	colorDangerTransparentDefaultBorder: 'colorDanger500',
	colorDangerTransparentActiveBorder: 'colorDanger500',
	colorDangerTransparentDisabledBorder: 'colorBasicTransparent300',

	colorControlFocus: 'colorBasic300',
	colorControlHover: 'colorBasic200',
	colorControlDefault: 'colorBasic100',
	colorControlActive: 'colorBasic300',
	colorControlDisabled: 'colorBasicTransparent300',
	colorControlFocusBorder: 'colorBasic500',
	colorControlHoverBorder: 'colorControlHover',
	colorControlDefaultBorder: 'colorControlDefault',
	colorControlActiveBorder: 'colorControlActive',
	colorControlDisabledBorder: 'colorControlDisabled',

	colorControlTransparentFocus: 'colorBasicControlTransparent300',
	colorControlTransparentHover: 'colorBasicControlTransparent200',
	colorControlTransparentDefault: 'colorBasicControlTransparent100',
	colorControlTransparentActive: 'colorBasicControlTransparent300',
	colorControlTransparentDisabled: 'colorBasicTransparent200',
	colorControlTransparentFocusBorder: 'colorBasic100',
	colorControlTransparentHoverBorder: 'colorBasic100',
	colorControlTransparentDefaultBorder: 'colorBasic100',
	colorControlTransparentActiveBorder: 'colorBasic100',
	colorControlTransparentDisabledBorder: 'colorBasicTransparent300',

	/* Backgrounds and borders - basic, alternative and primary  */

	backgroundBasicColor1: 'colorBasic100',
	backgroundBasicColor2: 'colorBasic200',
	backgroundBasicColor3: 'colorBasic300',
	backgroundBasicColor4: 'colorBasic400',

	borderBasicColor1: 'colorBasic100',
	borderBasicColor2: 'colorBasic200',
	borderBasicColor3: 'colorBasic300',
	borderBasicColor4: 'colorBasic400',
	borderBasicColor5: 'colorBasic500',

	backgroundAlternativeColor1: 'colorBasic800',
	backgroundAlternativeColor2: 'colorBasic900',
	backgroundAlternativeColor3: 'colorBasic1000',
	backgroundAlternativeColor4: 'colorBasic1100',

	borderAlternativeColor1: 'colorBasic800',
	borderAlternativeColor2: 'colorBasic900',
	borderAlternativeColor3: 'colorBasic1000',
	borderAlternativeColor4: 'colorBasic1100',
	borderAlternativeColor5: 'colorBasic1100',

	backgroundPrimaryColor1: 'colorPrimary500',
	backgroundPrimaryColor2: 'colorPrimary600',
	backgroundPrimaryColor3: 'colorPrimary700',
	backgroundPrimaryColor4: 'colorPrimary800',

	borderPrimaryColor1: 'colorBasic500',
	borderPrimaryColor2: 'colorBasic600',
	borderPrimaryColor3: 'colorBasic700',
	borderPrimaryColor4: 'colorBasic800',
	borderPrimaryColor5: 'colorBasic900',

	/* Text colors - general and status */

	textBasicColor: 'colorBasic800',
	textAlternateColor: 'colorBasic100',
	textControlColor: 'colorBasic100',
	textDisabledColor: 'colorBasicTransparent600',
	textHintColor: 'colorBasic600',

	textPrimaryColor: 'colorPrimaryDefault',
	textPrimaryFocusColor: 'colorPrimaryFocus',
	textPrimaryHoverColor: 'colorPrimaryHover',
	textPrimaryActiveColor: 'colorPrimaryActive',
	textPrimaryDisabledColor: 'colorPrimary400',

	textSuccessColor: 'colorSuccessDefault',
	textSuccessFocusColor: 'colorSuccessFocus',
	textSuccessHoverColor: 'colorSuccessHover',
	textSuccessActiveColor: 'colorSuccessActive',
	textSuccessDisabledColor: 'colorSuccess400',

	textInfoColor: 'colorInfoDefault',
	textInfoFocusColor: 'colorInfoFocus',
	textInfoHoverColor: 'colorInfoHover',
	textInfoActiveColor: 'colorInfoActive',
	textInfoDisabledColor: 'colorInfo400',

	textWarningColor: 'colorWarningDefault',
	textWarningFocusColor: 'colorWarningFocus',
	textWarningHoverColor: 'colorWarningHover',
	textWarningActiveColor: 'colorWarningActive',
	textWarningDisabledColor: 'colorWarning400',

	textDangerColor: 'colorDangerDefault',
	textDangerFocusColor: 'colorDangerFocus',
	textDangerHoverColor: 'colorDangerHover',
	textDangerActiveColor: 'colorDangerActive',
	textDangerDisabledColor: 'colorDanger400',

	/* Fonts and text styles - headings, subtitles, paragraphs, captions, button */

	fontFamilyPrimary: "unquote('Open Sans, sans-serif')",
	fontFamilySecondary: 'fontFamilyPrimary',

	textHeading1FontFamily: 'fontFamilySecondary',
	textHeading1FontSize: '2.25rem',
	textHeading1FontWeight: 700,
	textHeading1LineHeight: '3rem',

	textHeading2FontFamily: 'fontFamilySecondary',
	textHeading2FontSize: '2rem',
	textHeading2FontWeight: 700,
	textHeading2LineHeight: '2.5rem',

	textHeading3FontFamily: 'fontFamilySecondary',
	textHeading3FontSize: '1.875rem',
	textHeading3FontWeight: 700,
	textHeading3LineHeight: '2.5rem',

	textHeading4FontFamily: 'fontFamilySecondary',
	textHeading4FontSize: '1.625rem',
	textHeading4FontWeight: 700,
	textHeading4LineHeight: '2rem',

	textHeading5FontFamily: 'fontFamilySecondary',
	textHeading5FontSize: '1.375rem',
	textHeading5FontWeight: 700,
	textHeading5LineHeight: '2rem',

	textHeading6FontFamily: 'fontFamilySecondary',
	textHeading6FontSize: '1.125rem',
	textHeading6FontWeight: 700,
	textHeading6LineHeight: '1.5rem',

	textSubtitleFontFamily: 'fontFamilyPrimary',
	textSubtitleFontSize: '0.9375rem',
	textSubtitleFontWeight: 600,
	textSubtitleLineHeight: '1.5rem',

	textSubtitle2FontFamily: 'fontFamilyPrimary',
	textSubtitle2FontSize: '0.8125rem',
	textSubtitle2FontWeight: 600,
	textSubtitle2LineHeight: '1.5rem',

	textParagraphFontFamily: 'fontFamilyPrimary',
	textParagraphFontSize: '0.9375rem',
	textParagraphFontWeight: 400,
	textParagraphLineHeight: '1.25rem',

	textParagraph2FontFamily: 'fontFamilyPrimary',
	textParagraph2FontSize: '0.8125rem',
	textParagraph2FontWeight: 400,
	textParagraph2LineHeight: '1.125rem',

	textLabelFontFamily: 'fontFamilyPrimary',
	textLabelFontSize: '0.75rem',
	textLabelFontWeight: 700,
	textLabelLineHeight: '1rem',

	textCaptionFontFamily: 'fontFamilyPrimary',
	textCaptionFontSize: '0.75rem',
	textCaptionFontWeight: 400,
	textCaptionLineHeight: '1rem',

	textCaption2FontFamily: 'fontFamilyPrimary',
	textCaption2FontSize: '0.75rem',
	textCaption2FontWeight: 600,
	textCaption2LineHeight: '1rem',

	textButtonFontFamily: 'fontFamilyPrimary',
	textButtonFontWeight: 700,
	textButtonTinyFontSize: '0.625rem',
	textButtonTinyLineHeight: '0.75rem',
	textButtonSmallFontSize: '0.75rem',
	textButtonSmallLineHeight: '1rem',
	textButtonMediumFontSize: '0.875rem',
	textButtonMediumLineHeight: '1rem',
	textButtonLargeFontSize: '1rem',
	textButtonLargeLineHeight: '1.25rem',
	textButtonGiantFontSize: '1.125rem',
	textButtonGiantLineHeight: '1.5rem',

	/* Supporting variables - border radius, outline, shadow, divider */

	borderRadius: '0.25rem',

	outlineWidth: '0.375rem',
	outlineColor: 'colorBasicTransparent200',

	scrollbarColor: 'backgroundBasicColor4',
	scrollbarBackgroundColor: 'backgroundBasicColor2',
	scrollbarWidth: '0.3125rem',

	shadow: '0 0.5rem 1rem 0 rgba(44, 51, 73, 0.1)',

	dividerColor: 'borderBasicColor3',
	dividerStyle: 'solid',
	dividerWidth: '1px'
};
